language: python

cache:
  directories:
  - $HOME/.cache/pip

dist: bionic

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/frlearn
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4

matrix:
  include:
    - env: PYTHON_VERSION="3.7" NUMPY_VERSION="1.16.0" SCIPY_VERSION="1.1.0"
           SKLEARN_VERSION="0.22.0"
    - env: PYTHON_VERSION="3.7" NUMPY_VERSION="*" SCIPY_VERSION="*"
           SKLEARN_VERSION="nightly"

install:
  - source build_tools/travis/install.sh

script:
  - bash build_tools/travis/script.sh

after_success:
  - source build_tools/travis/after_success.sh
